import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ParticlesBackgorund from "./components/ParticlesBackgorund";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ParticlesBackgorund />

        <Link href={'/'}>Tareas</Link><br />
        <Link href={'/new'}>Nueva tarea</Link>
        {children}

      </body>
     
    </html>
  );
}
